### ISSUE TITLE
autocomplete acts weird when URL is in the bar.

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#25]

**Comment by ghost** [comment]
@nilnilnil Could you be more specific, or provide a screenshot?

**Comment by nilnilnil** [comment]
It stops completing.

![2014-05-12 09 12 57](https://cloud.githubusercontent.com/assets/347240/2944673/5abfda92-d9d7-11e3-9b54-6879f60ee175.png)

**Comment by ghost** [comment]
@nilnilnil 

It appears as though this is by design, and is also how the current live app behaves.

``` obj-c
if([newSearchText isEqualToString:[self.searchController validURLStringFromString:newSearchText]]) {
    // we're definitely editing a URL, don't bother with autocomplete.
    return;
}
```

The code checks to see if the search string contains a URL, and if so stops autocompleting since it assumes you're typing a web address and not searching.

We can change this behaviour though, if you like?

**Comment by nilnilnil** [comment]
I think we should.  I think anything that is a navigational search in the A/C like `facebook.com` should go there and anything else should be a search.  Nothing should stop the A/C from working though.

**Comment by ghost** [comment]
@nilnilnil I believe this is now fixed in the latest build. Could you please take it for a spin and let know? If you're happy, feel free to close.

**Comment by nilnilnil** [comment]
:+1:
