### ISSUE TITLE
default source list needs to be modifiable both adding and removing

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#26]
so we should have three lists.
user enabled
user disabled
default source list

if something isn't explicitly in either user list it should follow the default source list behavior.

**Comment by nilnilnil** [comment]
This is the last component that we really need to investigate.  I am happy to talk about it further, but we need to be sure it's exactly right because it's how we add and remove sources.  It could lead to major breakage that we can't address until we re-release.

**Comment by infinitekind** [comment]
ok, I think what you're asking is to make sure that we can both add new sources and remove sources without breaking things.  New sources should be enabled by default according to the "default" setting for each source in the JSON.  Updates to sources (based on the source name) shouldn't change the user's enabled/disabled setting for that source.  If a source is removed from the DDG list then it is also automatically removed from the user's list, whether it was enabled or not.

This is actually the current behaviour, although it doesn't use the three-lists approach.  What happens is that when the story view is first loaded/displayed the DDG source list is retrieved and any updates applied to the local sources without changing the enabled/disabled flag (but it does update the "default" setting).  Any new items are added to the list.  Any items that are in the local list but not the online list are removed from the local list altogether, so to remove an item from everyone's source list you just need to remove the entry from the online list.

So, I think the code is already doing what you're asking for (from a previous version) but please let me know if what I've described above doesn't match what you'd like.  We can definitely test this some more before the release, but I think we're otherwise ready and just need to merge from our repo and then merge or add in the save-image function.

**Comment by nilnilnil** [comment]
As per our conversation @micpringle is going to investigate the difficulty of arriving at this functionality with the rough core data schema currently in place.  The primary entry point to this code can be found here: https://github.com/duckduckgo/ios/blob/master/DuckDuckGo/DDGStoryFetcher.m#L51.

**Comment by ghost** [comment]
@nilnilnil 

I've just merged and pushed some commits which I think achieve all the behaviour we discussed on the call.
- There are now two fields, and three states that affect a feed.
  - `enabled`
    - `disabled`
    - `enabled`
    - `default`
  - `enabledByDefault`
    - `disabled`
    - `enabled`
- The `enabled` field takes precedence over the `enabledByDefault` field.
- When a new feed is added, the `enabled` field receives the state `default`, which means it falls back to the `enabledByDefault` field.
- You can change the `enabledByDefault` flag by changing the JSON, but this is only taken into account if the `enabled` state is `default`, otherwise the state set by the user takes precedence.
- You can delete a feed/source, but it will only be removed from a user's device if the `enabled` state is either `default` or `disabled`. If a user has explicitly enabled a feed then it'll remain until they disable it.
- I've added a `feedState` property which determines the proper state by querying both fields.
- The migration between the old model and the new model should be seamless, and won't affect any feeds a user has either enabled or disabled.

I've been testing this locally using Pow, Postman and a JSON file I created based on what's returned by the call to https://watrcoolr.duckduckgo.com/watrcoolr.js?o=json&type_info=1. It all appears to be working as intended :thumbsup: It'd be good if you could put it through it's paces too.

**Comment by nilnilnil** [comment]
Is there a way for me to look at the direct diff of these changes?  It sounds right! :smile:

**Comment by ghost** [comment]
@nilnilnil Viewing the [commit](https://github.com/duckduckgo/ios/commit/46772f63a976aee0aeae125a6747cd0f8d09ee23) would probably do it.

**Comment by ghost** [comment]
@nilnilnil 

Have you had a chance to review and test this at your end? Do you have any feedback?

**Comment by nilnilnil** [comment]
:+1: sounds good.

**Comment by ghost** [comment]
Closing as @sreilly has submitted a build to Apple that includes this functionality as stated [here](https://github.com/duckduckgo/ios/issues/34#issuecomment-45030360)
