### ISSUE TITLE
when searching bangs, the menu icon should be the bang favicon not the search icon

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#31]
I think this was the original behavior and we changed it to be more generic.  I'm not sure though.

**Comment by ghost** [comment]
![bang](https://cloud.githubusercontent.com/assets/20023/3102105/b1b069c2-e641-11e3-8ea2-1a63007f2685.png)

@nilnilnil Is it this one you're referring to?

**Comment by nilnilnil** [comment]
If it's that logo, it should remain the default orange one; otherwise, it should be the sites icon, if available.

**Comment by ghost** [comment]
I'm not sure I follow.

Should the magnifying glass not be used when searching bangs?

If the site icon isn't available, the magnifying glass placeholder is used, as shown in the screenshot above.

**Comment by nilnilnil** [comment]
Ah!  Sorry, I mean in the mini icon in the menu, not in the autosuggest view.

**Comment by ghost** [comment]
Ah, you mean the saved bang searches that appear in the slide-over menu?

**Comment by nilnilnil** [comment]
Yes, exactly.  I might be crazy, but I thought it might have been that way before the update?  I vaguely remember removing them to prevent clutter.

**Comment by ghost** [comment]
@nilnilnil 

![screen shot 2014-05-29 at 10 04 25](https://cloud.githubusercontent.com/assets/20023/3115913/89f06c46-e710-11e3-8869-1f70f623f4e8.png)

I've made the change, and used the existing !bang icon from the navigation bar button, but I think it might look better if @chrismorast could knock me up a new !bang icon that matched the style of the regular search icon; a solid background with a transparent icon (@1x 16x16 and @2x 32x32). What do you think?

As for using the sites' icon, this may be a touch awkward. The icons in the suggestions come as part of the JSON that's returned by the suggestion provider. The history items are either HistoryItem or Story Core Data entities, and only the Story entity stores a reference to it's favicon. So in order to implement this we'd need to change the way HistoryItems are created and stored, which would probably mean another Core Data migration. It'd be good to get your thoughts.

**Comment by nilnilnil** [comment]
I will talk with @chrismorast today and give you a definitive answer.  It's worth postponing until we have a real answer.

**Comment by ghost** [comment]
The old behaviour (_shown in the old App Store screenshots_) appears to have changed around March 2013 (_according to the git history_) when the app was migrated to Core Data. Prior to that, more info was cached; after the change only the search text was stored.

**Comment by ghost** [comment]
@nilnilnil Did you speak to @chrismorast about getting an updated icon?

**Comment by nilnilnil** [comment]
We spoke about it briefly.  I'm good with a !bang specific icon instead of individual ones.

**Comment by chrismorast** [comment]
Here's an updated icon for the bangs.
![icon_bang](https://cloud.githubusercontent.com/assets/7061920/3175759/4249d948-ebfe-11e3-8252-b87c9f7691a3.png)
![icon_bang 2x](https://cloud.githubusercontent.com/assets/7061920/3175758/424829a4-ebfe-11e3-9067-38d8c6300b48.png)
