### ISSUE TITLE
iPad has default iOS icon

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#34]

**Comment by samgreen** [comment]
Resolved in #35 :)

**Comment by ghost** [comment]
@nilnilnil I'll be able to fix this when I'm back in tomorrow.

**Comment by nilnilnil** [comment]
![2cecab6c-cbf5-11e3-8c84-9a8a0fd2cc22](https://cloud.githubusercontent.com/assets/347240/3161861/f5849ca2-eb2f-11e3-8f25-eb288f36f632.png)

@samgreen

**Comment by chrismorast** [comment]
Please use this new icon asset globally...
![duckduckgo_1024x1024](https://cloud.githubusercontent.com/assets/7061920/3165442/318397ca-eb54-11e3-9468-443cf9855d7d.png)

**Comment by infinitekind** [comment]
Got it, thanks!  A new build (v5.2) has been created and submitted to Apple that includes this icon as well as @micpringle's changes to improve the updating of story feeds.

**Comment by chrismorast** [comment]
Sorry to chime in late on this comment but the header is meant to be semi-transparent. @micpringle had mentioned that it was but looking closely I see that it's not. Any particular reasoning behind this?

![img_3659](https://cloud.githubusercontent.com/assets/7061920/3167663/3ea47df2-eb72-11e3-9d45-c7869e5fc9d3.png)
![img_3658](https://cloud.githubusercontent.com/assets/7061920/3167662/3ea066e0-eb72-11e3-8061-19da119f1956.png)

**Comment by infinitekind** [comment]
If I remember correctly Mic mentioned that it was using the default system navigation bar which is supposed to provide the blur over the content that scrolls behind it.  Checking the code, we use a UINavigationBar but I think we'd need to use a full UINavigationController in order to get the blur.  That may be tricky to add without rewriting a ton of the navigation code that we were handling manually.  It'd be simple to make the nav bar translucent, but I'll check with Mic in the morning to see about getting the full blurred nav bar.

**Comment by chrismorast** [comment]
Sounds good. I'd opt for full opacity if we can't get the blurred effect.

**Comment by ghost** [comment]
@chrismorast 

I've taken a look at blurring the navigation bar. Here's what I've found:
- The current view hierarchy isn't a standard setup (i.e. it's not using `UINavigationController`) which means we'd need to update each different view controller manually and independently.
- Part of the current setup limits the size of the content to the size of the screen minus the height of the status bar and navigation bar. We can obviously change this to match how iOS 7 layouts should work, but... 
- Because of the _unusual_ setup, the content would then appear behind the navigation bar. In order to fix this we would need to manipulate the `contentInset`. The only thing with this is that the PTR control already manipulates the `contentInset` internally, so we'd need to take this into account and may even have to change how that control works internally.
- Finally, even if we fix all of the above, the PTR control would sit directly underneath the navigation bar when the stories view in not scrolled by the user; this means by default the navigation bar on the stories view would have a reddish tint.

It's totally your call, as we're happy to go ahead and try and resolve all these issues, I just wanted to bring them to your attention first. The other option would be to simply put it on the back-burner until we begin looking at the _from-the-ground-up rewrite_, if that's still on the cards.

/cc @nilnilnil

**Comment by nilnilnil** [comment]
I don't think it's worth it until we revisit our mobile strategy.  Please hold on this.

**Comment by ghost** [comment]
@nilnilnil No problem.

Closing then since @sreilly fixed the original iPad icon issue.
