### ISSUE TITLE
Images don't update when feed images changes on backend.

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#38]
@micpringle @infinitekind @yegg @kablamo

**Comment by ghost** [comment]
@nilnilnil 

Would the URL for the image, that's delivered as part of the feed, change when you switch the images at your end, or would it remain the same and you'd simply swap the actual files?

The reason I ask is because the image cache currently uses the story id as it's lookup key, so in that setup has no way of knowing the image has changed. However, I'm thinking now that if the URL does change we could use the actual URL as the key, and that way it would automatically download and cache any new images.

**Comment by kablamo** [comment]
@nilnilnil @micpringle the s3 image url changes when we switch the images.  I'm betting thats the url you are discussing but I'm not 100% on how that end of things works if there are additional layers of caching.

**Comment by ghost** [comment]
@nilnilnil @kablamo 

Ok, so it sounds like it would make more sense to use the image URL as the cache lookup key, rather than using the story id like it currently does. This would mean that whenever the image URL changed for a story, the cache would notice and force the download of the new image.

Let me know if you're happy for me to go ahead and make the change.

**Comment by nilnilnil** [comment]
:+1:

**Comment by ghost** [comment]
@nilnilnil 

We've tested this locally and it works as expected, but it wouldn't hurt if you wanted to download the build from Hockey and give it a test yourself by refreshing the stories, changing an image on the backend, and then refreshing again.

**Comment by nilnilnil** [comment]
I can't install it on my primary that runs iOS 8.  Is that a known issue?  @yegg is going to try.

**Comment by ghost** [comment]
@nilnilnil Could be a Hockey <-> iOS 8 compatibility issue, but I can't say for sure.
