### ISSUE TITLE
Enhance the out-of-box experience for contributors

### ISSUE THREAD

**Issue by marcpalmer** [duckduckgo/ios-search-and-stories#49]
Silly little things, but it would be nice to make it a no-brainer for people to clone and build.

I did this with master (1de348fd) and had the following issues building with Xcode 6.1 (not sure whether or not this is relevant, I don't think so):
1. Document the `git submodule update --init` command required to pull down the dependencies, to save numpties like me who don't use submodules (cocoapods!) from hunting around
2. The files in the AFNetworking group in the Xcode project appear to be "Relative to Group", rather than "Relative to Project" and as such the files can't be found by Xcode — at least on 6.1
3. Document the need to install mogenerator and download link
4. Look at updating mogenerator build script which uses `/usr/local/bin/mogenerator` — the latest mogenerator when installed on my disk lives in `/usr/bin` at least on Yosemite

With these steps I have managed to build and run it under 6.1

**Comment by nilnilnil** [comment]
What I am hearing is we should probably just introduce a cocoapod.  Do you think that would be sufficient? /cc @micpringle @infinitekind @sreilly

**Comment by marcpalmer** [comment]
It would mean changing the app to use cocoapods to retrieve dependencies. I'm not sure that's necessary (and is controversial to some), but it would eliminate problems (1) and (2). 

I think it also would mean you can, I think, be more controlled in what versions of the dependencies each tag of the app is using.

**Comment by sreilly** [comment]
We currently control the version of the dependencies by pointing the submodules at specific commits.  I have no problem switching to cocoapods but the current submodules are also working fine.  Since we currently have four separate submodules (not sure how many are actually still used or how many are available as pods) I'd vote for keeping it the same until there was a pressing need.

Updating the contributor instructions is a great idea.

**Comment by nilnilnil** [comment]
This is pretty old, and we've not gotten feedback about this recently. Closing for now.
