### ISSUE TITLE
Reccomendation: Convert to Swift

### ISSUE THREAD

**Issue by jaredStef** [duckduckgo/ios-search-and-stories#51]
Last summer Apple unveiled its new programming language Swift to the world. Eventually Obj - C is going to be phased out. Due to the great new features and new syntax it makes coding iPhone apps even easier. I feel that then more people may contribute to this project if we converted to Swift. I want to help do this, but before I wrote some code I figured it should be discussed.

**Comment by sreilly** [comment]
It would certainly be fun to update to Swift, but I think it might be better to begin new projects in Swift rather than spend the substantial effort to convert existing code, not to mention all of the 3rd party libraries that might also be involved.  Maybe there's room for a new app idea that uses DDG?

**Comment by nilnilnil** [comment]
Closing based on the fact we're sticking with Obj-C for now. Perhaps if we refactor in big ways, we'll switch.
