### ISSUE TITLE
Add story title to tweet

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#61]
When sharing a story to Twitter, we currently only pre-fill the URL of the story. Can you also include the story title and the via-DDG-phrase? So, that would be: "{Title} {URL} via DuckDuckGo for iOS"

**Comment by sreilly** [comment]
this is fixed in the upcoming build

**Comment by thm** [comment]
The new popup window is a good idea! Can we change the color of the Cancel and Post links? if so, can you make that #de5833 or rgba(222,88,51,1)

In addition, it looks like the new tweet text format has only been updated in the share option in the drop-down menu in a feed, but not yet in the sharing options from the browser option-bar (prev, next, favorite, _share_)

**Comment by sreilly** [comment]
ok, changed the top bar background color and text button colors, but we don't have control over each individual button's colors.  I've also changed the sharing text and URL to be embedded in a slightly cleaner way.  Basically before we were providing two things to every available share outlet: 1) the sharing text with URL embedded in it, and 2) the raw URL.  Both items (text and URL) are necessary because without the raw URL we can't share to URL-based things like Safari, Pocket, Instapaper, etc.  The text is also obviously necessary, but embedding the URL in the text string would cause things like the Twitter, iMessage and Email messages to include the URL twice - once in the text and once appended to the end of the message (from the raw URL).  The only way I could think to make this clean was to remove the embedded URL from the shared text but include the raw URL.  This seems to "attach" the URL properly to tweets while not having the link appear twice in the text of shared iMessages/Emails.  As I write this I realise I've forgotten to make the same change in the browser toolbar share function, so let's leave this one open until I fix that in the morning :)

**Comment by thm** [comment]
@sreilly Ah, here's that explanation about the URLs! Is this the one you referred to in #60?

With the links-color change above I meant the Twitter popup, but I think we shouldn't change that after all as described in #60. I'll close this and we can continue the discussion on the URL-issue in #60
