### ISSUE TITLE
Brief blinks and visual bugs

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#68]
1. When I go back to a Stories feed (stories, favorites or recents) the story images sometimes briefly blink. I assume the page is being refreshed, but I'd prefer to do that in the background (without transitions)
2. Sometimes, above and below the search field, two white lines appear
   ![lines](https://cloud.githubusercontent.com/assets/1379822/9609870/6b2cc6d4-50d6-11e5-8a44-769d6c3709eb.png)

**Comment by sreilly** [comment]
@thm I think the problem was that the stories view was being refreshed even if there were no stories added or removed.  I've removed the call to refresh the view in those cases and it seems to solve the problem.  I haven't encountered the double-lines, but can you try and see under what situations they appear?  Is it maybe associated with rotation?

**Comment by thm** [comment]
No need to reassign if an issue isn't fixed yet :). It's not associated with rotation. It seems to happen most often when I enter the app from the app-switcher, or when I enter the app-switcher

**Comment by sreilly** [comment]
@thm I haven't been able to reproduce this at all.  Are you on an iPhone6?  Can you tell me which version of iOS?  Just to confirm: the blinking problem should be resolved, and we're working on just the white lines problem?

**Comment by thm** [comment]
Yes, iPhone 6 (iOS 8.4.1, app v607), and just for the white lines. The blinking seems to be fixed!
