### ISSUE TITLE
Story grid in masonry view is not complete

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#83]
This is on iPad as well as iPhone 6 landscape view.
![img_0388](https://cloud.githubusercontent.com/assets/7061920/9695497/36ddbd6e-5317-11e5-80d5-a1f9714f9b6d.PNG)

**Comment by sreilly** [comment]
Hi Chris,
Can you clarify what the problem is? Should we leave off the remaindered stories or use an alternate layout for the last row?

**Comment by chrismorast** [comment]
Any way we can fill that last spot on the bottom right with a story or is this something that we're limiting in our feed? @nilnilnil , do you know?

**Comment by thm** [comment]
@chrismorast if it's a limitation, then we could solve it by design too:

![end-of-feed](https://cloud.githubusercontent.com/assets/1379822/9698942/0977607a-53ce-11e5-88c7-8bd01ef2d5ae.jpg)
![end-of-feed-2](https://cloud.githubusercontent.com/assets/1379822/9698944/0bccfac4-53ce-11e5-8b8c-f8ce37703b5c.jpg)

**Comment by chrismorast** [comment]
Perhaps this would be a good opportunity to call out the sources setting. It could be simply adding another sentence stating, "Want more? You can add sources in Settings" (or something along those lines).

**Comment by thm** [comment]
@chrismorast awesome idea :+1:

**Comment by thm** [comment]
@sreilly
1. for each story-slot that isn't filled on a page, can you insert a #e0e0e0 background-color like pictured in the screenshot below?
   ![IMG1](https://cloud.githubusercontent.com/assets/1379822/10023405/492c0c98-6152-11e5-9388-55e48a427cb9.jpg)
2. For the last row — that likely won't fit perfectly well — can you make sure that we don't allow the user to scroll to it and stay there, but rather, after releasing revert back to aligning the first row to the top? On pages that already scroll (ie. the main Stories feed) we only have to fill out the current row since the feed already takes up more than you can see at a time. (click image below for further documentation)
   ![IMG2](https://cloud.githubusercontent.com/assets/1379822/10023409/550f9412-6152-11e5-8c9c-6938e3a15c72.jpg)

Please, let me know if anything is unclear
