### ISSUE TITLE
Left and right-edge swipe navigation in Search

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#89]
@sreilly When viewing an image that's zoomed in (so that the horizontal scrollbar appears), a swipe from the left-edge of the screen to go back doesn't work. Can we force this so that it always works regardless of the page's contents?

**Comment by sreilly** [comment]
I think the left-edge swipe doesn't work in this case because the tap-and-move gesture is being absorbed by the web page itself to pan and zoom the photo.  If you use two fingers to zoom out you can then use the swipe-from-edge gesture to navigate back up a level.  I'll see if there's a flag that we can set to override that behaviour.

**Comment by sreilly** [comment]
@thm Yeah, I think this one's going to have to be left alone, at least until we get more time to use a more modern API for the web viewer.  I wouldn't consider this a bug for now because it's the intended behaviour of the UIWebView implementation.

**Comment by thm** [comment]
I'm renaming this issue so we can start working on the left-edge and right-edge swiping to go back and forward in the web view on iOS 8+
